[package]
name = "chunk-model"
version = "0.1.0"
edition = "2021"

[lib]
name = "chunk_model"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# Optional helpers to keep the base crate light.
time = []
hash = []
schema = []

